- name: Create Docker networks on Windows
  win_shell: "docker network create {{ item.name }}"
  with_items: "{{ docker.networks }}"
  ignore_errors: true
  when: is_windows

- name: Create Docker networks on Linux
  community.docker.docker_network:
    name: "{{ item.name }}"
  with_items: "{{ docker.networks }}"
  when: is_linux